import type { DealCategory } from "./types";

const RULES: { category: DealCategory; keywords: string[] }[] = [
  {
    category: "Kött & chark",
    keywords: [
      "kött",
      "fläsk",
      "nöt",
      "kyckling",
      "korv",
      "bacon",
      "skinka",
      "färs",
      "biff",
      "lamm",
      "kalkon",
      "chark",
      "salami",
      "falukorv",
      "grill",
      "entrecote",
      "ytterfilé",
      "köttfärs",
    ],
  },
  {
    category: "Fisk & skaldjur",
    keywords: [
      "fisk",
      "lax",
      "torsk",
      "räk",
      "skaldjur",
      "sill",
      "makrill",
      "krabba",
      "musslor",
      "tonfisk",
      "sej",
      "kolja",
    ],
  },
  {
    category: "Frukt & grönt",
    keywords: [
      "frukt",
      "grönt",
      "äpple",
      "banan",
      "tomat",
      "gurka",
      "sallad",
      "potatis",
      "lök",
      "morot",
      "paprika",
      "bär",
      "citron",
      "avokado",
      "broccoli",
      "spenat",
      "svamp",
      "kål",
    ],
  },
  {
    category: "Mejeri & ost",
    keywords: [
      "mjölk",
      "ost",
      "yoghurt",
      "grädde",
      "smör",
      "fil",
      "kvarg",
      "créme",
      "bregott",
      "keso",
      "ägg",
      "margarin",
    ],
  },
  {
    category: "Bröd & bakverk",
    keywords: [
      "bröd",
      "limpa",
      "fralla",
      "knäcke",
      "kaka",
      "bullar",
      "muffins",
      "tårta",
      "bakverk",
      "croissant",
      "baguette",
      "pizza",
      "paj",
    ],
  },
  {
    category: "Skafferi",
    keywords: [
      "pasta",
      "ris",
      "konserv",
      "sås",
      "olja",
      "krydda",
      "soppa",
      "müsli",
      "flingor",
      "havregryn",
      "mjöl",
      "socker",
      "kaffe",
      "te",
      "marmelad",
      "honung",
      "buljong",
    ],
  },
  {
    category: "Fryst",
    keywords: [
      "fryst",
      "frysta",
      "glass",
      "färskfryst",
      "fryspizza",
      "frysta",
    ],
  },
  {
    category: "Dryck",
    keywords: [
      "dryck",
      "läsk",
      "juice",
      "vatten",
      "öl",
      "vin",
      "cider",
      "saft",
      "energidryck",
      "kolsyrad",
      "smoothie",
    ],
  },
  {
    category: "Snacks & godis",
    keywords: [
      "chips",
      "godis",
      "choklad",
      "snacks",
      "nötter",
      "popcorn",
      "kex",
      "gelé",
      "lakrits",
      "marabou",
    ],
  },
  {
    category: "Hushåll",
    keywords: [
      "disk",
      "tvätt",
      "papper",
      "servett",
      "städ",
      "blöja",
      "toalett",
      "hushåll",
      "sop",
      "rengöring",
      "tork",
      "dukar",
    ],
  },
];

export function categorizeDeal(name: string, rawCategory?: string): DealCategory {
  const haystack = `${name} ${rawCategory ?? ""}`.toLowerCase();

  for (const rule of RULES) {
    if (rule.keywords.some((kw) => haystack.includes(kw))) {
      return rule.category;
    }
  }

  return "Övrigt";
}
